stages:
    - build
    - test

variables:
    NCS_INSTALL_DIR: /root/ncs/
    TOOLCHAIN_VERSION: v2.6.0
    SDK_VERSION: v2.6.0

default:
    image: ubuntu:latest

compile:
    stage: build
    before_script:
        - apt-get update && apt-get install wget make cmake -y
        - wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil -O /usr/local/bin/nrfutil && chmod +x /usr/local/bin/nrfutil
        - nrfutil install toolchain-manager
        - nrfutil toolchain-manager install --ncs-version $TOOLCHAIN_VERSION --install-dir $NCS_INSTALL_DIR
        - cd $NCS_INSTALL_DIR
        - nrfutil toolchain-manager launch -- west init -m https://github.com/nrfconnect/sdk-nrf --mr $SDK_VERSION || if [ $? -eq 1 ]; then echo "[WARN] Could not initialize SDK"; fi
        - nrfutil toolchain-manager launch -- west update
        - nrfutil toolchain-manager launch -- west zephyr-export
    cache:
        key: $CI_COMMIT_REF_NAME
        when: always
        paths:
            - $NCS_INSTALL_DIR
    script:
        - source $NCS_INSTALL_DIR/zephyr/zephyr-env.sh
        - ls -alh
        - echo "[TODO] Build project"

lint:
    stage: test
    script:
        - echo "[TODO] Run linter/static analyser"
